version: '3.5'
services:
  banxico_db:
    container_name: banxico_db
    image: mysql:5.7.32
    volumes:
      - ./backups/:/var/backups/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=banxico_db
